export const serviciosList = [
"Alergia",
  "Alimentación",
  "Anestesiología",
  "Auditoría y Gestión Clínica",
  "Bacteriología",
  "Cardiología",
  "Cirugía",
  "CODEI",
  "Dermatología",
  "Diabetologia",
  "Diagnóstico por Imágenes",
  "División Clínica Médica",
  "Dto. Área Programática",
  "Dto. Consultorios Externos",
  "Dto. Cirugía",
  "Dto. Diagnóstico y tratamiento",
  "Dto. Medicina",
  "Dto. Técnico",
  "Dto. Urgencias",
  "Electrofisiología",
  "Endocrino",
  "Enfermería",
  "Farmacia",
  "Gastroenterología",
  "Genética",
  "Ginecología",
  "Hematología",
  "Hemodinamia",
  "Hemoterapia",
  "Infectologia",
  "Kinesiología",
  "Laboratorio",
  "Nefrología",
  "Neonatología",
  "Neumonología",
  "Neurocirugía",
  "Neurología",
  "Nutrición",
  "Obstetricia",
  "Odontología",
  "Oftalmología",
  "Oncología",
  "Otorrinolaringología",
  "Patología",
  "Pediatría",
  "Plástica",
  "Promoción Protección de la Salud",
  "Quirófano e Instrumentación",
  "Reumatología",
  "Salud Escolar",
  "Salud Mental",
  "Servicio Social",
  "Terapia Intensiva",
  "Traumatología",
  "Urología"
]